// Openings explorer: the full Lichess opening book (CC0) + SAN-line resolver.
//
// openings-db.json is generated by scripts/build-openings-list.mjs from the
// lichess-org/chess-openings TSVs: every named ECO line, with its mainline as
// canonical SAN. Each entry can be listed, searched and replayed move-by-move.
// The live opening label on the board still comes from
// window.api.openings.lookup(fen): this dataset powers the browsable index, the
// continuation scan and the "matched ply" reading on the name plate.

import { Chess } from 'chessops/chess'
import { parseFen, makeFen, INITIAL_FEN } from 'chessops/fen'
import { parseSan, makeSan } from 'chessops/san'
import { makeUci } from 'chessops/util'
import OPENINGS_DB from './openings-db.json'

interface RawOpening {
  eco: string
  name: string
  san: string[]
}

/** The five ECO volumes, A..E. */
export type EcoVolume = 'A' | 'B' | 'C' | 'D' | 'E'

export interface OpeningEntry {
  /** Stable id for React keys / selection. */
  id: string
  name: string
  /** ECO code for the listed mainline. */
  eco: string
  /** ECO volume letter, which is the axis the index's volume tabs filter on. */
  volume: EcoVolume
  /** Mainline as SAN tokens, e.g. ['e4','e5','Nf3','Nc6','Bb5']. */
  line: string[]
  /** Parent opening. The name before ':' ("Sicilian Defense"), or the whole
   *  name when the entry has no variation suffix. */
  family: string
  /** Variation suffix. The name after ':' ("Najdorf Variation"); '' when the
   *  entry IS the family mainline (no colon in the book name). */
  variation: string
  /** What a row under its family header prints. The variation suffix; bare
   *  mainline entries become "Main line". A family can carry the same label
   *  twice at different depths (the book lists "Sicilian Defense" at B20, B27
   *  and B50), so a repeated label gets its last move appended
   *  ("Main line · 2…d6") and two rows stop reading as the same line. */
  variationLabel: string
}

/** A parent opening with every line the book files under it: the top level of
 *  the index. You open a NAME, and the family's variations are what is inside.
 *  This is the level the book is browsable at; 3,733 lines in one list is not. */
export interface OpeningFamily {
  /** Unique key = the family name. */
  key: string
  name: string
  /** Lines in the family, its own mainline entry included. */
  count: number
  /** Mainline entry first when the book lists one, then ECO then depth, so a
   *  family reads root-first and sibling systems stay together. */
  variations: OpeningEntry[]
}

/** A single resolved ply in an opening line. */
export interface LineMove {
  san: string
  uci: string
  /** FEN of the position AFTER this move. */
  fen: string
}

/** One named reply available from a position, for the continuations table. */
export interface Continuation {
  /** The reply itself, in SAN. */
  san: string
  /** Name it leads to, family prefix dropped when the book gives one. */
  name: string
  eco: string
  /** Named lines in the book below this reply, the named one included. */
  below: number
}

/** "1.e4" / "2…d6": the last move of a line, tagged with its move number. */
function lastMoveTag(line: string[]): string {
  const i = line.length - 1
  if (i < 0) return ''
  return `${Math.floor(i / 2) + 1}${i % 2 === 0 ? '.' : '…'}${line[i]}`
}

function volumeOf(eco: string): EcoVolume {
  const letter = eco[0]?.toUpperCase()
  return letter === 'A' || letter === 'B' || letter === 'C' || letter === 'D' || letter === 'E'
    ? letter
    : 'A'
}

// ---- Full opening book (generated; sorted by name) -----------------------

export const OPENINGS: OpeningEntry[] = (OPENINGS_DB as RawOpening[]).map((o, i) => {
  const colon = o.name.indexOf(':')
  const variation = colon === -1 ? '' : o.name.slice(colon + 1).trim()
  return {
    id: `${o.eco}-${i}`,
    name: o.name,
    eco: o.eco,
    volume: volumeOf(o.eco),
    line: o.san,
    family: (colon === -1 ? o.name : o.name.slice(0, colon)).trim(),
    variation,
    variationLabel: variation || 'Main line' // disambiguated in the FAMILIES build
  }
})

/** The index's filter tabs, in ECO order. The letter is what the tab prints;
 *  the label is the volume's own subject matter, and titles the tab. */
export const ECO_VOLUMES: ReadonlyArray<{ letter: EcoVolume; label: string }> = [
  { letter: 'A', label: 'A · Flank and irregular' },
  { letter: 'B', label: 'B · Semi-open games' },
  { letter: 'C', label: 'C · Open games and French' },
  { letter: 'D', label: 'D · Closed and semi-closed' },
  { letter: 'E', label: 'E · Indian defences' }
]

/**
 * The book as families, biggest first.
 *
 * Book names follow the "Family: Variation" convention, so grouping on the
 * prefix reconstructs the opening tree: 3,733 lines collapse to 148 names.
 * Popularity order is variation count, which is the best proxy the CC0 book
 * carries (the Sicilian's 385 named lines against a one-line gambit); the
 * index re-weights this per volume tab, since a family can straddle volumes.
 */
export const FAMILIES: OpeningFamily[] = (() => {
  const byName = new Map<string, OpeningEntry[]>()
  for (const o of OPENINGS) {
    const list = byName.get(o.family)
    if (list) list.push(o)
    else byName.set(o.family, [o])
  }

  const out: OpeningFamily[] = []
  for (const [name, variations] of byName) {
    variations.sort((a, b) => {
      // The family's own mainline leads, then ECO order, then depth: the
      // family reads root -> deeper book positions, and sibling systems
      // (Najdorf B90-B99) stay adjacent.
      if (!a.variation !== !b.variation) return a.variation ? 1 : -1
      if (a.eco !== b.eco) return a.eco < b.eco ? -1 : 1
      if (a.line.length !== b.line.length) return a.line.length - b.line.length
      return a.name.localeCompare(b.name)
    })

    // 3,733 entries carry only 3,167 distinct names, so a family can print the
    // same label twice at different depths. A repeated label takes its own last
    // move, which is the thing that actually differs.
    const seen = new Map<string, number>()
    for (const v of variations) seen.set(v.variationLabel, (seen.get(v.variationLabel) ?? 0) + 1)
    for (const v of variations) {
      if ((seen.get(v.variationLabel) ?? 0) > 1) {
        const tag = lastMoveTag(v.line)
        if (tag) v.variationLabel = `${v.variationLabel} · ${tag}`
      }
    }

    out.push({ key: name, name, count: variations.length, variations })
  }

  out.sort((a, b) => b.count - a.count || a.name.localeCompare(b.name))
  return out
})()

// Every line keyed by its SAN, so "what is this position called" and "how deep
// does the book still know it" are map reads rather than scans. The generator
// emits no two entries with the same move order, checked when this was written.
const BY_LINE: Map<string, OpeningEntry> = (() => {
  const m = new Map<string, OpeningEntry>()
  for (const o of OPENINGS) if (!m.has(o.line.join(' '))) m.set(o.line.join(' '), o)
  return m
})()

/** The book entry for exactly this move order, if the book names it. */
export function entryForLine(path: readonly string[]): OpeningEntry | null {
  return BY_LINE.get(path.join(' ')) ?? null
}

/**
 * The deepest named line that this move order still follows. Walking back from
 * the end is what makes "matched ply 5" a real reading: it is the ply at which
 * the book last recognised the position, whether or not it recognises this one.
 */
export function deepestBookLine(path: readonly string[]): OpeningEntry | null {
  for (let i = path.length; i > 0; i--) {
    const hit = BY_LINE.get(path.slice(0, i).join(' '))
    if (hit) return hit
  }
  return null
}

/**
 * The named replies to a position, most-carried first.
 *
 * Every entry the book holds below this move order is bucketed by its next
 * move. The bucket's size is what the table prints as "Below", so a descent is
 * chosen on how much book lies under it rather than guessed. What the reply is
 * CALLED comes from the entry at exactly one ply deeper when the book names
 * one, and otherwise from the shallowest line under it, because a reply the
 * book only names three plies later still leads there.
 */
export function continuationsFor(path: readonly string[]): Continuation[] {
  const depth = path.length
  const buckets = new Map<string, OpeningEntry[]>()
  outer: for (const o of OPENINGS) {
    if (o.line.length <= depth) continue
    for (let i = 0; i < depth; i++) if (o.line[i] !== path[i]) continue outer
    const san = o.line[depth]
    const bucket = buckets.get(san)
    if (bucket) bucket.push(o)
    else buckets.set(san, [o])
  }

  const out: Continuation[] = []
  for (const [san, list] of buckets) {
    let lead = list[0]
    for (const o of list) {
      if (o.line.length === depth + 1) {
        lead = o
        break
      }
      if (o.line.length < lead.line.length) lead = o
    }
    out.push({ san, name: lead.variation || lead.name, eco: lead.eco, below: list.length })
  }
  out.sort((a, b) => b.below - a.below || a.san.localeCompare(b.san))
  return out
}

/** A SAN line as the index prints it: "1.e4 e5 2.Nf3 Nc6 3.Bb5". */
export function formatMoves(line: readonly string[]): string {
  const parts: string[] = []
  for (let i = 0; i < line.length; i += 2) {
    const black = line[i + 1]
    parts.push(black ? `${i / 2 + 1}.${line[i]} ${black}` : `${i / 2 + 1}.${line[i]}`)
  }
  return parts.join(' ')
}

/**
 * Resolve a SAN line into per-ply { san, uci, fen }. Walks from the initial
 * position; stops defensively on the first illegal/unparseable token (curated
 * data should never trip this, but never throw into the UI).
 */
export function resolveLine(sanLine: readonly string[]): LineMove[] {
  const pos = Chess.fromSetup(parseFen(INITIAL_FEN).unwrap()).unwrap()
  const out: LineMove[] = []
  for (const token of sanLine) {
    const move = parseSan(pos, token)
    if (!move) break
    // Re-derive SAN so display is canonical (e.g. disambiguation/checks).
    const san = makeSan(pos, move)
    const uci = makeUci(move)
    pos.play(move)
    out.push({ san, uci, fen: makeFen(pos.toSetup()) })
  }
  return out
}
