// gameSounds: per-game default SoundName mapping for the games platform.
//
// NOTE FOR BOARD BUILDERS (P2 wave 2): this module is the single source of
// truth for which sound a game's board plays. Do NOT hard-code SoundNames in
// board components: look the kind up here (soundsFor(kind)) and play through
// useSound()/getSoundManager() as usual. GameSpec.moveMeta(state, move) may
// return an explicit `sound` for a specific move (e.g. othello marking a
// flipping move as 'discFlip'); when it does, that wins over the defaults:
//
//   const sounds = soundsFor(kind)
//   const meta = spec.moveMeta(state, move)
//   play(meta.sound ?? (meta.capture ? sounds.capture : sounds.place))
//
// The samples behind the game-specific names live in assets/sounds/games/
// (generated by scripts/gen-game-sounds.mjs, verified by
// scripts/check-game-sounds.mjs) and resolve under ALL three sound themes;
// a theme can override any of them by shipping its own file (see
// SoundManager's shared-pool comment). Keys cover every GameKind in the
// kernel union (including P2/P3 kinds not yet in the registry) so board
// work never blocks on this file.

import type { GameKind } from '../games/kernel'
import type { SoundName } from './SoundManager'

export interface GameSoundMap {
  /** A normal move / placement. */
  place: SoundName
  /** A capturing move (flips for othello, jumps for checkers, ...). */
  capture: SoundName
  /** The local player (or either player, OTB) wins / game reaches a result. */
  win: SoundName
  /** Game-start cue; defaults to the app-wide 'gameStart' when omitted. */
  gameStart?: SoundName
}

const CHESS_LIKE: GameSoundMap = { place: 'move', capture: 'capture', win: 'gameEnd' }

/** Wooden-disc chess relatives (xiangqi/janggi pieces are flat wooden discs). */
const DISC_CHESS: GameSoundMap = { place: 'discPlace', capture: 'capture', win: 'gameEnd' }

const GAME_SOUNDS: Record<GameKind, GameSoundMap> = {
  // chess family. Chessops (P1)
  chess: CHESS_LIKE,
  chess960: CHESS_LIKE,
  crazyhouse: CHESS_LIKE,
  atomic: CHESS_LIKE,
  antichess: CHESS_LIKE,
  kingofthehill: CHESS_LIKE,
  threecheck: CHESS_LIKE,
  horde: CHESS_LIKE,
  racingkings: CHESS_LIKE,
  // chess family. Ffish (P2)
  xiangqi: DISC_CHESS,
  janggi: DISC_CHESS,
  makruk: CHESS_LIKE, // upright pieces, western-style set-down
  shogi: { place: 'shogiPiece', capture: 'capture', win: 'gameEnd' },
  placement: CHESS_LIKE,
  // go family
  go: { place: 'goStone', capture: 'capture', win: 'gameEnd', gameStart: 'gameStartGong' },
  gomoku: { place: 'goStone', capture: 'goStone', win: 'gameEnd' }, // no captures in practice
  // draughts family
  checkers: { place: 'discPlace', capture: 'pieceSlideCapture', win: 'gameEnd' },
  'checkers-intl': { place: 'discPlace', capture: 'pieceSlideCapture', win: 'gameEnd' },
  // grid family
  othello: { place: 'discPlace', capture: 'discFlip', win: 'gameEnd' },
  connect4: { place: 'discDrop', capture: 'discDrop', win: 'gameEnd' }, // no captures
  hex: { place: 'penStroke', capture: 'penStroke', win: 'gameEnd' }, // no captures
  morris: { place: 'discPlace', capture: 'pieceSlideCapture', win: 'gameEnd' },
  tictactoe: { place: 'penStroke', capture: 'penStroke', win: 'gameEnd' } // no captures
}

/** Default sound mapping for a game. Total over GameKind. Never undefined. */
export function soundsFor(kind: GameKind): GameSoundMap {
  return GAME_SOUNDS[kind]
}

export { GAME_SOUNDS }
