#!/usr/bin/env python3
"""Regenerate _gallery/pages.js from the d01..d10 directories.

The gallery has to run by double-clicking index.html, which means no fetch() and
no reading of the iframe document (both are blocked for file:// origins). So the
twenty style/feel sheets and the forty screens are snapshotted into one JS file
that index.html loads with a plain <script> tag.

Run this again after editing anything inside a dNN directory:

    python3 _gallery/build-pages.py
"""

import json
import os
import re
import time

LAB = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(LAB, "_gallery", "pages.js")

DIRS = ["d%02d" % n for n in range(1, 11)]
SCREENS = {
    "home": "home.html",
    "mobile": "home.mobile.html",
    "games": "games.html",
    "school": "school.html",
}


def read(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def pairing(readme, key):
    """Pull one 'Combines well with:' / 'Fights with:' block out of a README.

    The lines wrap, so a block runs from its label to the next blank line or the
    next label.
    """
    lines = readme.splitlines()
    out = []
    grabbing = False
    for line in lines:
        low = line.strip().lower()
        if low.startswith(key.lower()):
            grabbing = True
            out.append(line.strip()[len(key):].strip())
            continue
        if grabbing:
            if not low or re.match(r"^(combines well with|fights with|contract note|note)\b", low):
                break
            out.append(line.strip())
    return " ".join(x for x in out if x).strip()


def refs(text):
    """Directions named in a pairing line, as zero-padded numbers."""
    found = []
    for m in re.finditer(r"\bd?(0[1-9]|10)\b", text):
        n = m.group(1)
        if n not in found:
            found.append(n)
    return found


data = {"generated": time.strftime("%Y-%m-%d %H:%M"), "dirs": {}}

for d in DIRS:
    nn = d[1:]
    base = os.path.join(LAB, d)
    readme = read(os.path.join(base, "README.md"))
    good = pairing(readme, "Combines well with:")
    bad = pairing(readme, "Fights with:")
    entry = {
        "style": read(os.path.join(base, "style.css")),
        "feel": read(os.path.join(base, "feel.css")),
        "screens": {k: read(os.path.join(base, v)) for k, v in SCREENS.items()},
        "goodText": good,
        "goodRefs": [x for x in refs(good) if x != nn],
        "badText": bad,
        "badRefs": [x for x in refs(bad) if x != nn],
    }
    data["dirs"][nn] = entry

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("/* GENERATED by _gallery/build-pages.py. Do not edit by hand. */\n")
    fh.write("window.LAB = ")
    json.dump(data, fh, ensure_ascii=False)
    fh.write(";\n")

print("wrote %s (%.0f KB)" % (OUT, os.path.getsize(OUT) / 1024.0))
for nn, e in data["dirs"].items():
    print("  d%s good=%s bad=%s" % (nn, ",".join(e["goodRefs"]) or "-", ",".join(e["badRefs"]) or "-"))
